<!-- MHonArc v2.6.18 -->
<!--X-Subject: Re: [sup&#45;devel] [issue64] Crash on sup start -->
<!--X-From-R13: Unhgr Vbcr <rtNtnhgr.irgfw.pbz> -->
<!--X-Date: Tue, 24 Aug 2010 14:21:12 &#45;0700 (PDT) -->
<!--X-Message-Id: 1282684816&#45;sup&#45;340@dolk -->
<!--X-Content-Type: text/plain -->
<!--X-Reference: 1265688194.03.0.035958787068.issue64@masanjin.net -->
<!--X-Head-End-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Re: [sup-devel] [issue64] Crash on sup start</title>
<link rev="made" href="mailto:eg@gaute.vetsj.com">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<hr>
[<a href="msg01008.html">Date Prev</a>][<a href="msg00792.html">Date Next</a>][Thread Prev][<a href="msg01172.html">Thread Next</a>][<a href="maillist.html#00967">Date Index</a>][<a href="threads.html#00967">Thread Index</a>]
<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h1>Re: [sup-devel] [issue64] Crash on sup start</h1>
<hr>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul>
<li><em>To</em>: sup-devel &lt;<a href="mailto:sup-devel%40rubyforge.org">sup-devel@rubyforge.org</a>&gt;</li>
<li><em>Subject</em>: Re: [sup-devel] [issue64] Crash on sup start</li>
<li><em>From</em>: Gaute Hope &lt;<a href="mailto:eg%40gaute.vetsj.com">eg@gaute.vetsj.com</a>&gt;</li>
<li><em>Date</em>: Tue, 24 Aug 2010 23:21:10 +0200</li>
<li><em>In-reply-to</em>: &lt;<a href="msg01405.html">1265688194.03.0.035958787068.issue64@masanjin.net</a>&gt;</li>
<li><em>References</em>: &lt;<a href="msg01405.html">1265688194.03.0.035958787068.issue64@masanjin.net</a>&gt;</li>
<li><em>User-agent</em>: Sup/git</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
<hr>
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre>Excerpts from anonymous's message of 2010-02-09 05:03:14 +0100:
&gt; 
&gt; New submission from anonymous:
&gt; 
&gt; sup crashed after I sent an email, and won't start anymore.
&gt; 
&gt; This is with the latest git version. Ubuntu/Karmic.
&gt; 
&gt; [Tue Feb 09 14:59:30 +1100 2010] ERROR: oh crap, an exception
&gt; ----------------------------------------------------------------
&gt; I'm very sorry. It seems that an error occurred in Sup. Please
&gt; accept my sincere apologies. Please submit the contents of
&gt; /home/brian/.sup/exception-log.txt and a brief report of the
&gt; circumstances to <a  rel="nofollow" href="http://masanjin.net/sup-bugs/">http://masanjin.net/sup-bugs/</a> so that I might
&gt; address this problem. Thank you!
&gt; 
&gt; Sincerely,
&gt; William
&gt; ----------------------------------------------------------------
&gt; --- RuntimeError from thread: load threads for thread-index-mode
&gt; 
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:348:in `find_docid'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:353:in `find_doc'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:363:in `get_entry'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:77:in `build_message'
&gt; /usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:372:in `synchronize'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:77:in `build_message'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:121:in `each_id_by_date'
&gt; /home/brian/tree/sup/lib/sup/thread.rb:332:in `call'
&gt; /home/brian/tree/sup/lib/sup/thread.rb:332:in `load_n_threads'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:121:in `each_id_by_date'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:114:in `each_id'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:114:in `each'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:114:in `each_id'
&gt; /home/brian/tree/sup/lib/sup/xapian_index.rb:121:in `each_id_by_date'
&gt; /home/brian/tree/sup/lib/sup/thread.rb:328:in `load_n_threads'
&gt; /home/brian/tree/sup/lib/sup/modes/thread-index-mode.rb:630:in 
&gt; `__unprotected_load_n_threads'
&gt; (eval):12:in `load_n_threads'
&gt; /home/brian/tree/sup/lib/sup/modes/thread-index-mode.rb:614:in 
&gt; `load_n_threads_background'
&gt; /home/brian/tree/sup/lib/sup.rb:77:in `reporting_thread'
&gt; /home/brian/tree/sup/lib/sup.rb:75:in `initialize'
&gt; /home/brian/tree/sup/lib/sup.rb:75:in `new'
&gt; /home/brian/tree/sup/lib/sup.rb:75:in `reporting_thread'
&gt; /home/brian/tree/sup/lib/sup/modes/thread-index-mode.rb:613:in 
&gt; `load_n_threads_background'
&gt; /home/brian/tree/sup/lib/sup/modes/thread-index-mode.rb:684:in 
&gt; `__unprotected_load_threads'
&gt; (eval):12:in `load_threads'
&gt; /home/brian/tree/sup/bin/sup:226
&gt; 
&gt; Brian May
&gt; 
&gt; ----------
&gt; messages: 155
&gt; nosy: anonymous
&gt; priority: bug
&gt; ruby_version: 4.2
&gt; status: unread
&gt; sup_version: git
&gt; title: Crash on sup start
&gt; 

This just happened to me as well. Commenting out the fail lets me start up.

- gaute
</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
<hr>
<!--X-Follow-Ups-End-->
<!--X-References-->
<ul><li><strong>References</strong>:
<ul>
<li><strong><a name="01405" href="msg01405.html">[sup-devel] [issue64] Crash on sup start</a></strong>
<ul><li><em>From:</em> anonymous &lt;sup-bugs@masanjin.net&gt;</li></ul></li>
</ul></li></ul>
<!--X-References-End-->
<!--X-BotPNI-->
<ul>
<li>Prev by Date:
<strong><a href="msg01008.html">[sup-devel] [issue119] RuntimeError from thread: load threads	for	thread-index-mode</a></strong>
</li>
<li>Next by Date:
<strong><a href="msg00792.html">[sup-devel] [PATCH] fix problem with Content-Type in mail header</a></strong>
</li>
<li>Next by thread:
<strong><a href="msg01172.html">Re: [sup-talk] [PATCH] If we have a COLUMNS environment variable,	wrap to that instead of 80.</a></strong>
</li>
<li>Index(es):
<ul>
<li><a href="maillist.html#00967"><strong>Date</strong></a></li>
<li><a href="threads.html#00967"><strong>Thread</strong></a></li>
</ul>
</li>
</ul>

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
</body>
</html>
