<!-- MHonArc v2.6.18 -->
<!--X-Subject: Re: [sup&#45;talk] exception &#45;&#45;&#45; RuntimeError from thread: poll after loading inbox -->
<!--X-From-R13: Unhgr Vbcr <rtNtnhgr.irgfw.pbz> -->
<!--X-Date: Wed, 9 Nov 2011 11:25:13 &#45;0800 (PST) -->
<!--X-Message-Id: CABKe4Mut=UnKFBt91UxgJu5NxOJ57iQPv464K=e5mS_jQUn1tA@mail.gmail.com -->
<!--X-Content-Type: text/plain -->
<!--X-Reference: 56777.143.205.193.62.1320657425.squirrel@lavabit.com -->
<!--X-Reference: 1320700740&#45;sup&#45;9219@tilus.net -->
<!--X-Reference: 1929.143.205.216.123.1320746264.squirrel@lavabit.com -->
<!--X-Head-End-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Re: [sup-talk] exception --- RuntimeError from thread: poll after loading inbox</title>
<link rev="made" href="mailto:eg@gaute.vetsj.com">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<hr>
[<a href="msg00297.html">Date Prev</a>][<a href="msg00036.html">Date Next</a>][<a href="msg00024.html">Thread Prev</a>][<a href="msg00036.html">Thread Next</a>][<a href="maillist.html#00040">Date Index</a>][<a href="threads.html#00040">Thread Index</a>]
<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h1>Re: [sup-talk] exception --- RuntimeError from thread: poll after loading inbox</h1>
<hr>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul>
<li><em>To</em>: Sup users &lt;<a href="mailto:sup-talk%40rubyforge.org">sup-talk@rubyforge.org</a>&gt;</li>
<li><em>Subject</em>: Re: [sup-talk] exception --- RuntimeError from thread: poll after loading inbox</li>
<li><em>From</em>: Gaute Hope &lt;<a href="mailto:eg%40gaute.vetsj.com">eg@gaute.vetsj.com</a>&gt;</li>
<li><em>Date</em>: Wed, 9 Nov 2011 20:25:13 +0100</li>
<li><em>Delivered-to</em>: <a href="mailto:eg%40gaute.vetsj.com">eg@gaute.vetsj.com</a></li>
<li><em>In-reply-to</em>: &lt;<a href="msg00024.html">1929.143.205.216.123.1320746264.squirrel@lavabit.com</a>&gt;</li>
<li><em>References</em>: &lt;<a href="msg00281.html">56777.143.205.193.62.1320657425.squirrel@lavabit.com</a>&gt;	&lt;<a href="msg00278.html">1320700740-sup-9219@tilus.net</a>&gt;	&lt;<a href="msg00024.html">1929.143.205.216.123.1320746264.squirrel@lavabit.com</a>&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
<hr>
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre>I am getting the same error now, after upgraded ruby and gems..

bin/sup-sync:11: warning: method redefined; discarding old to_s
/home/gaute/dev/ruby/sup.git/lib/sup.rb:18:in `id': wrong id called on
{&quot;uri&quot;=&gt;&quot;maildir:///home/gaute/.mail/gaute.vetsj.com/Gmail.All_Mail&quot;,
&quot;usual&quot;=&gt;true, &quot;archived&quot;=&gt;false, &quot;id&quot;=&gt;3, &quot;labels&quot;=&gt;[&quot;inbox&quot;]}
(RuntimeError)
	from /home/gaute/dev/ruby/sup.git/lib/sup/source.rb:207:in `block (2
levels) in load_sources'
	from /home/gaute/dev/ruby/sup.git/lib/sup/source.rb:207:in `map'
	from /home/gaute/dev/ruby/sup.git/lib/sup/source.rb:207:in `block in
load_sources'
	from /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	from /home/gaute/dev/ruby/sup.git/lib/sup/source.rb:206:in `load_sources'
	from /home/gaute/dev/ruby/sup.git/lib/sup/util.rb:572:in `method_missing'
	from /home/gaute/dev/ruby/sup.git/lib/sup/index.rb:96:in `load'
	from bin/sup-sync:100:in `&lt;main&gt;'

(same error when trying to start sup).

Also Ruby GPGME 2.0 seems to not be compatible with old API.

- gaute

On Tue, Nov 8, 2011 at 10:57 AM,  &lt;hollunder@lavabit.com&gt; wrote:
&gt;&gt; hollunder, 2011-11-07 11:17:
&gt;&gt;&gt; I wonder what component is at fault.
&gt;&gt;
&gt;&gt; Looks like it fails when adding new messages from maildir to index.
&gt;&gt; Somehow term_docids for the id of newly received message yields more
&gt;&gt; than one documents from index. &#xA0;Could it be that one of the new
&gt;&gt; messages in your maildir has a mangled message id?
&gt;&gt;
&gt;&gt; I'm not familiar with offlineimap. &#xA0;You might need some extra steps or
&gt;&gt; a completely different approach here, but: You could try to (back up
&gt;&gt; and temporarily) move new messages out of your inbox (using mutt etc)
&gt;&gt; and then retry with sup.
&gt;&gt;
&gt;&gt; --
&gt;&gt; Tero Tilus ## 050 3635 235 ## <a  rel="nofollow" href="http://tero.tilus.net/">http://tero.tilus.net/</a>
&gt;&gt; _______________________________________________
&gt;&gt; sup-talk mailing list
&gt;&gt; sup-talk@rubyforge.org
&gt;&gt; <a  rel="nofollow" href="http://rubyforge.org/mailman/listinfo/sup-talk">http://rubyforge.org/mailman/listinfo/sup-talk</a>
&gt;&gt;
&gt;&gt;
&gt;
&gt; Thanks,
&gt; I'll try that kind of stuff if I manage to, never used another mail reader
&gt; than sup.
&gt; Anyway, today a new ruby update came along and even after rebuilding
&gt; everything I could think of, including sup, sup doesn't start anymore. Not
&gt; sure it's the same issue.
&gt;
&gt; Also tried sup-git, but it doesn't seem to build at all.
&gt;
&gt; $ sup
&gt; /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will
&gt; be deprecated in the future, use String#encode instead.
&gt; /usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext/runtime/locale_path.rb:20:
&gt; Use RbConfig instead of obsolete and deprecated Config.
&gt; [2011-11-08 10:48:46 +0100] ERROR: oh crap, an exception
&gt; ----------------------------------------------------------------
&gt; I'm very sorry. It seems that an error occurred in Sup. Please
&gt; accept my sincere apologies. Please submit the contents of
&gt; /home/murks/.sup/exception-log.txt and a brief report of the
&gt; circumstances to <a  rel="nofollow" href="http://masanjin.net/sup-bugs/">http://masanjin.net/sup-bugs/</a> so that I might
&gt; address this problem. Thank you!
&gt;
&gt; Sincerely,
&gt; William
&gt; ----------------------------------------------------------------
&gt; --- RuntimeError from thread: main
&gt; wrong id called on
&gt; {&quot;uri&quot;=&gt;&quot;maildir:/home/murks/.imap/lavabit_murks_local/Inbox&quot;,
&gt; &quot;usual&quot;=&gt;true, &quot;archived&quot;=&gt;false, &quot;id&quot;=&gt;1, &quot;labels&quot;=&gt;[&quot;murks_lavabit&quot;,
&gt; &quot;personal&quot;]}
&gt; /usr/lib/ruby/gems/1.9.1/gems/sup-0.12.1/lib/sup.rb:18:in `id'
&gt; /usr/lib/ruby/gems/1.9.1/gems/sup-0.12.1/lib/sup/source.rb:207:in `block
&gt; (2 levels) in load_sources'
&gt; /usr/lib/ruby/gems/1.9.1/gems/sup-0.12.1/lib/sup/source.rb:207:in `map'
&gt; /usr/lib/ruby/gems/1.9.1/gems/sup-0.12.1/lib/sup/source.rb:207:in `block
&gt; in load_sources'
&gt; /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
&gt; /usr/lib/ruby/gems/1.9.1/gems/sup-0.12.1/lib/sup/source.rb:206:in
&gt; `load_sources'
&gt; /usr/lib/ruby/gems/1.9.1/gems/sup-0.12.1/lib/sup/util.rb:609:in
&gt; `method_missing'
&gt; /usr/lib/ruby/gems/1.9.1/gems/sup-0.12.1/lib/sup/index.rb:92:in `load'
&gt; /usr/lib/ruby/gems/1.9.1/gems/sup-0.12.1/lib/sup/util.rb:609:in
&gt; `method_missing'
&gt; /usr/lib/ruby/gems/1.9.1/gems/sup-0.12.1/bin/sup:154:in `&lt;module:Redwood&gt;'
&gt; /usr/lib/ruby/gems/1.9.1/gems/sup-0.12.1/bin/sup:69:in `&lt;top (required)&gt;'
&gt; /usr/bin/sup:19:in `load'
&gt; /usr/bin/sup:19:in `&lt;main&gt;'
&gt;
&gt;
&gt;
&gt;
&gt; _______________________________________________
&gt; sup-talk mailing list
&gt; sup-talk@rubyforge.org
&gt; <a  rel="nofollow" href="http://rubyforge.org/mailman/listinfo/sup-talk">http://rubyforge.org/mailman/listinfo/sup-talk</a>
&gt;
</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
<hr>
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00036" href="msg00036.html">Re: [sup-talk] exception --- RuntimeError from thread: poll after loading inbox</a></strong>
<ul><li><em>From:</em> Gaute Hope &lt;eg@gaute.vetsj.com&gt;</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<ul><li><strong>References</strong>:
<ul>
<li><strong><a name="00281" href="msg00281.html">[sup-talk] exception --- RuntimeError from thread: poll after	loading inbox</a></strong>
<ul><li><em>From:</em> hollunder@lavabit.com</li></ul></li>
<li><strong><a name="00278" href="msg00278.html">Re: [sup-talk] exception --- RuntimeError from thread: poll after	loading inbox</a></strong>
<ul><li><em>From:</em> Tero Tilus &lt;tero@tilus.net&gt;</li></ul></li>
<li><strong><a name="00024" href="msg00024.html">Re: [sup-talk] exception --- RuntimeError from thread: poll after loading inbox</a></strong>
<ul><li><em>From:</em> hollunder@lavabit.com</li></ul></li>
</ul></li></ul>
<!--X-References-End-->
<!--X-BotPNI-->
<ul>
<li>Prev by Date:
<strong><a href="msg00297.html">[sup-talk] exception on start after ruby upgrade</a></strong>
</li>
<li>Next by Date:
<strong><a href="msg00036.html">Re: [sup-talk] exception --- RuntimeError from thread: poll after loading inbox</a></strong>
</li>
<li>Previous by thread:
<strong><a href="msg00024.html">Re: [sup-talk] exception --- RuntimeError from thread: poll after loading inbox</a></strong>
</li>
<li>Next by thread:
<strong><a href="msg00036.html">Re: [sup-talk] exception --- RuntimeError from thread: poll after loading inbox</a></strong>
</li>
<li>Index(es):
<ul>
<li><a href="maillist.html#00040"><strong>Date</strong></a></li>
<li><a href="threads.html#00040"><strong>Thread</strong></a></li>
</ul>
</li>
</ul>

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
</body>
</html>
